DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEM_EMAIL"	VARCHAR2(100)		NOT NULL,
	"MEM_NICK"	NVARCHAR2(8)		NOT NULL UNIQUE,
	"MEM_PASSWORD"	VARCHAR2(4000)		NULL,
	"MEM_ROLE"	VARCHAR2(2)		NOT NULL,
	"MEM_ENABLED"	NUMBER	DEFAULT 1	NOT NULL,
	"MEM_TYPE"	CHAR(1)		NOT NULL,
	"MEM_JOIN_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_QUIT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MEM_NICK" IS '회원 닉네임(한글 2~8자), UNIQUE';

COMMENT ON COLUMN "MEMBER"."MEM_PASSWORD" IS '비밀번호 (영문, 숫자 포함 8~20자)';

COMMENT ON COLUMN "MEMBER"."MEM_ROLE" IS '회원 권한 등급 [일반회원(1), 관리자(2), 마스터(3)]';

COMMENT ON COLUMN "MEMBER"."MEM_ENABLED" IS '활성 여부 [비활성(0), 활성(1)]';

COMMENT ON COLUMN "MEMBER"."MEM_TYPE" IS 'SNS 여부 [이메일(T), 카카오(K), 네이버(N), 구글(G)]';

COMMENT ON COLUMN "MEMBER"."MEM_JOIN_DATE" IS '가입날짜';

COMMENT ON COLUMN "MEMBER"."MEM_QUIT_DATE" IS '탈퇴날짜';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_EMAIL"
);

