select * from place ORDER BY CONTENTID;

DECLARE
	vn_num1 NUMBER := 1;
BEGIN
	LOOP
		INSERT INTO PLACE (TYPE, CONTENTID, CONTENTTYPEID, ADD1, AREACODE, MAPX, MAPY, TITLE, GETTIME) 
SELECT 100, AREA_CODE, 100, AREA_ADRESS, AREA_CODE, AREA_X, AREA_Y, AREA_LANDMARK, '20240707' FROM AREA WHERE AREA_CODE = vn_num1;
		vn_num1 := vn_num1 + 1;			-- java의 vn_num2++;과 같음.
		EXIT WHEN vn_num1 > 8;			-- 10보다 크면 루프종료.
	END LOOP;
END;
/

DECLARE
	vn_num1 NUMBER := 31;
BEGIN
	LOOP
		INSERT INTO PLACE (TYPE, CONTENTID, CONTENTTYPEID, ADD1, AREACODE, MAPX, MAPY, TITLE, GETTIME) 
SELECT 100, AREA_CODE, 100, AREA_ADRESS, AREA_CODE, AREA_X, AREA_Y, AREA_LANDMARK, '20240707' FROM AREA WHERE AREA_CODE = vn_num1;
		vn_num1 := vn_num1 + 1;			-- java의 vn_num2++;과 같음.
		EXIT WHEN vn_num1 > 39;			-- 10보다 크면 루프종료.
	END LOOP;
END;
/